backpack:
  - name: Гигиена
    items:
      - name: Гель для рук
        count: 1
      - name: Влажные салфетки
        count: 1
      - name: Зубная щетка
        count: 3
      - name: Зубная паста
        count: 2
      - name: Шампунь
        count: 1
      - name: Детский шампунь
        count: 1
      - name: Крем для рук
        count: 1
      - name: Крем для лица
        count: 2
      - name: Крем для Дианы
        count: 1
      - name: Лосьон для Дианы
        count: 1
      - name: Крем от загара
        count: 1
      - name: Гигиеничка
        count: 1
      - name: Резинки для волос
        count: 1
      - name: Резинки для волос Диана
        count: 2
      - name: Расческа
        count: 1
      - name: Ополаскиватель для рта
        count: 1
      - name: Щипчики
        count: 1
      - name: Бритвы
        count: 2
      - name: Носовые платочки
        count: 2
      - name: Перчатки для рук
        count: 2
      - name: Заколка
        count: 1
      - name: Заколка Диана
        count: 2
      - name: Прокладки
        count: 20
  - name: С собой
    items:
      - name: Паспорта
        count: 3
      - name: Водительские права
        count: 1
      - name: ПМЖ
        count: 3
      - name: Копия свидетельства о рождении
        count: 1
      - name: Деньги
        count: 500
      - name: Страховки
        count: 3
      - name: Страховка ERGO
        count: 1
      - name: Кредитка
        count: 2
      - name: Фотоаппарат
        count: 1
      - name: Зарядка для фотоаппарата
        count: 1
      - name: Зарядка для телефона
        count: 2
      - name: Зарядка для часов
        count: 2
      - name: Путеводитель
        count: 1
      - name: Билеты
        count: 6
      - name: Солнечные очки
        count: 2
      - name: Аккумулятор
        count: 1
      - name: Наушники для Дианы
        count: 1
      - name: Иголочка от айфона
        count: 1
      - name: Планшет
        count: 1
      - name: Сушка для обуви
        count: 1
      - name: Очки Юля
        count: 1
  - name: Одежда
    items:
      - name: Носки Андрей
        count: 'days'
      - name: Трусы Андрей
        count: 'days'
      - name: Носки Юля
        count: 'days'
      - name: Трусы Юля
        count: 'days'
      - name: Плавки
        count: 1
      - name: Купальник
        count: 2
      - name: Футболки Андрей
        count: 'days / 2'
      - name: Кофта Андрей
        count: 1
      - name: Джинсы Андрей
        count: 1
      - name: Футболки Юля
        count: 'days / 2'
      - name: Кофта Юля
        count: 1
      - name: Штаны Юля
        count: 1
      - name: Платье Юля
        count: 1
      - name: Футболки для сна
        count: 2
      - name: Колготки
        count: 1
      - name: Тапки Юля
        count: 1
      - name: Тапки Андрей
        count: 1
  - name: Одежда для Дианы
    items:
      - name: Штаны и колкотки
        count: 'nights'
      - name: Футболки и платья
        count: 'days / 2'
      - name: Трусы
        count: 'nights'
      - name: Носки
        count: 'nights'
      - name: Купальник
        count: 1
      - name: Шапка
        count: 1
      - name: Перчатки
        count: 2
      - name: Кепка
        count: 1
      - name: Тапки
        count: 1
      - name: Кофта
        count: 1
      - name: Пижама
        count: 1
  - name: В чем едем
    items:
      - name: Куртка Юля
        count: 1
      - name: Куртка Андрей
        count: 1
      - name: Куртка Диана
        count: 1
      - name: Ботинки Юля
        count: 1
      - name: Ботинки Андрей
        count: 1
      - name: Ботинки Диана
        count: 1
      - name: Штаны Юля
        count: 1
      - name: Штаны Андрей
        count: 1
      - name: Штаны Диана
        count: 1
      - name: Футболка Юля
        count: 1
      - name: Футболка Андрей
        count: 1
      - name: Футболка Диана
        count: 1
      - name: Кофта Юля
        count: 1
      - name: Кофта Андрей
        count: 1
      - name: Кофта Диана
        count: 1
      - name: Шапка Юля
        count: 1
      - name: Шапка Андрей
        count: 1
      - name: Шапка Диана
        count: 1
      - name: Шарф Диана
        count: 1
      - name: Перчатки Диана
        count: 1
      - name: Колготки
        count: 1
  - name: Аптечка
    items:
      - name: Ибупрофен
        count: 8
      - name: Парацетамол
        count: 8
      - name: Детский ибупрофен
        count: 1
      - name: Пластырь
        count: 4
      - name: Градусник
        count: 1
      - name: Капли в нос
        count: 1
      - name: Капли в глаза
        count: 1
      - name: Momegalen
        count: 1
      - name: Ацикловир
        count: 1
  - name: Вещи для Дианы
    items:
      - name: Видеоняня
        count: 1
      - name: Книги
        count: 3
      - name: Раскраска
        count: 1
      - name: Тетрадка
        count: 3
      - name: Листочки
        count: 20
      - name: Карандаши и фломастеры
        count: 10
      - name: Игрушки
        count: 5
      - name: Игрушка в самолет
        count: 1
      - name: Магнитики
        count: 1
      - name: Наклейки
        count: 2
      - name: Нарукавники
        count: 1
      - name: Очки для плавания
        count: 2
      - name: Накладки на туалет
        count: 20
      - name: Хрустики
        count: 1
      - name: Сладости
        count: 1
